AWSTemplateFormatVersion: 2010-09-09
Description: Template for load-balancer

Parameters: 
  #Project params
  Project:
    Description: Name of the project
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Stage:
    Description: Stage Name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  #network parameters
  LoadBalancerSGId:
    Description: Reference to the LoadBalancerSG from SSM
    Type: AWS::SSM::Parameter::Value<String>
  PublicSubnetAId:
    Description: Reference to the Public subnet A from SSM
    Type: AWS::SSM::Parameter::Value<String>
  PublicSubnetBId:
    Description: Reference to the Public subnet B from SSM
    Type: AWS::SSM::Parameter::Value<String>


Resources: 
  #Load balancer
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: !Sub ${Project}-${Stage}-${Component}-lb
      SecurityGroups:
        - !Ref LoadBalancerSGId
      Subnets:
        - !Ref PublicSubnetAId
        - !Ref PublicSubnetBId
      Type: application
      Tags: 
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-lb
  #Load balancer parameters
  LoadBalancerArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Description: !Sub Stores ${Project}-${Stage}-${Component} load balancer arn
      Name: !Sub /${Project}/${Stage}/${Component}/lb/arn
      Tier: Standard
      Type: String
      Value: !Ref LoadBalancer
      Tags: 
        Name: !Sub ${Project}-${Stage}-${Component}-lb-arn
      
  LoadBalancerUrlParam:
    Type: AWS::SSM::Parameter
    Properties:
      Description: !Sub Stores ${Project}-${Stage}-${Component} load balancer url
      Name: !Sub /${Project}/${Stage}/${Component}/lb/url
      Tier: Standard
      Type: String
      Value: !GetAtt LoadBalancer.DNSName
      Tags: 
        Name: !Sub ${Project}-${Stage}-${Component}-lb-url

Outputs:
  LoadBalancerArn:
    Description:  The Arn of the loadbalancer
    Value: !Ref LoadBalancer
  LoadBalancerArnParamName:
    Description: The name of the SSM param that stores arn of the lb
    Value: !Ref LoadBalancerArnParam
  LoadBalancerUrl:
    Description:  The Url of the loadbalancer
    Value: !GetAtt LoadBalancer.DNSName
  LoadBalancerUrlParamName:
    Description: The name of the SSM param that stores url of the lb
    Value: !Ref LoadBalancerUrlParam