AWSTemplateFormatVersion: 2010-09-09
Description: Network template for NAT Gateways

Parameters: 
  #Project params
  Project:
    Description: Name of the project
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Stage:
    Description: Stage Name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$

  #Networking params
  PublicSubnetId:
    Description: The name of SSM parameter that stores public subnet name
    Type: AWS::SSM::Parameter::Value<String>
  PrivateRouteTable:
    Description: The name of SSM parameter that stores private route table id
    Type: AWS::SSM::Parameter::Value<String>

Resources:
  ### Nat gateway resources
  NatGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  
  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnetId
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-nat-gateway
        
  ### Default private route ( private -> nat -> public )

  DefaultPrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

Outputs:
  NatGatewayId:
    Description: Nat Gateway Id
    Value: !Ref NatGateway
  NatGatewayEIP:
    Description: Nat Gateway EIP
    Value: !Ref NatGatewayEIP