AWSTemplateFormatVersion: 2010-09-09
Description: Template for jumphost instance

Parameters: 
  # Project info
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Component name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  #Instance setup
  ImageId:
    Description: Id of latest amazon-linux-2 AMI
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  InstanceType:
    Description: Size of jumphost EC2 instance
    Type: String
    Default: t2.micro
  KeyPairName:
    Description: Name of the key pair to auth VM
    Type: String

  # SSM references
  JumpHostSGId:
    Description: Jumphost id from SSM store
    Type: AWS::SSM::Parameter::Value<String>
  PublicSubnetId:
    Description: The id of public subnet from SSM
    Type: AWS::SSM::Parameter::Value<String>

Resources:
  JumpHostInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPairName
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref JumpHostInstanceProfile
      SubnetId: !Ref PublicSubnetId
      SecurityGroupIds:
        - !Ref JumpHostSGId
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          sudo yum update -y
          sudo amazon-linux-extras enable postgresql11
          sudo yum clean metadata
          sudo yum install postgresql -y
          sudo yum install jq -y
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-jumphost-instance

  JumpHostInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref JumpHostInstanceRole

  JumpHostInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: JumpHostPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: GetSecretValue
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                  - secretsmanager:ListSecretVersionIds
                  - secretsmanager:ListSecrets
                Resource:
                  !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${Project}/${Stage}/*
           

Outputs:
  JumpHostInstanceId:
    Description: The ID of the Jump Host Instance
    Value: !Ref JumpHostInstance
  JumpHostInstancePublicIp:
    Description: The public ip of the Jump Host Instance
    Value: !GetAtt JumpHostInstance.PublicIp