AWSTemplateFormatVersion: 2010-09-09
Description: Template for autoscaling group for launching jumphost instance based on schedule 

Parameters:
  #Project params
  Project:
    Description: Name of the project
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Stage:
    Description: Stage Name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  #Jump host launch template
  JumpHostLaunchTemplateId:
    Description: The reference to the SSM parameter that stores id of the jump host launch template
    Type: AWS::SSM::Parameter::Value<String>
  JumpHostLaunchTemplateVersion:
    Description: Version No. of the jumphost launch template
    Type: String
    Default: ''
  JumpHostLaunchTemplateLatestVersion:
    Description: The reference to the SSM parameter that stores latest version of the jump host launch template
    Type: AWS::SSM::Parameter::Value<String>
  #Network
  PublicSubnetAId:
    Description: The reference to the SSM parameter that stores id of the public subnet a
    Type: AWS::SSM::Parameter::Value<String>
  
Conditions:
  UseProvidedLaunchTemplateVersion: !Not [ !Equals [!Ref JumpHostLaunchTemplateVersion, ''] ]

Resources: 
  JumpHostAutoscaling:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      HealthCheckType: EC2
      LaunchTemplate:
        LaunchTemplateId: !Ref JumpHostLaunchTemplateId
        Version: !If
          - UseProvidedLaunchTemplateVersion
          - !Ref JumpHostLaunchTemplateVersion
          - !Ref JumpHostLaunchTemplateLatestVersion
      MaxSize: '1'
      MinSize: '1'
      DesiredCapacity: '1'
      VPCZoneIdentifier:
        - !Ref PublicSubnetAId
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-jumphost-asg
          PropagateAtLaunch: false

  JumpHostScaleOut:
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: 
        Ref: JumpHostAutoscaling
      DesiredCapacity: 1
      MaxSize: 1
      MinSize: 1
      Recurrence: "0 7 * * 1-5"

  JumpHostScaleIn:
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: 
        Ref: JumpHostAutoscaling
      DesiredCapacity: 0
      MaxSize: 0
      MinSize: 0
      Recurrence: "0 16 * * 1-5"

Outputs:
  JumpHostASGName:
    Description: The name of jumphost ASG
    Value: !Ref JumpHostAutoscaling